/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author helpdesk
 */
public class form_multilista extends javax.swing.JFrame {
 private Multilista list;
 private Nodo_Padre padre;
 private Nodo_Hijo hijo;
    
    /**
     * Creates new form form_multilista
     */
    public form_multilista() {
        initComponents();
        list=new Multilista();
        padre=new Nodo_Padre();
        hijo=new Nodo_Hijo();
    }

    public void nuevo()
    {
        txid.setText("");
        txip.setText("");
        txid.requestFocus();
    }        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txip = new javax.swing.JTextField();
        btsavepc = new javax.swing.JButton();
        btsavesala = new javax.swing.JButton();
        btmostrar = new javax.swing.JButton();
        btsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Multilistas -Gestión de pc- ");
        getContentPane().setLayout(null);

        jLabel1.setText("Id Sala");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 50, 14);

        txid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txidActionPerformed(evt);
            }
        });
        getContentPane().add(txid);
        txid.setBounds(90, 20, 130, 30);

        jLabel3.setText("Ip");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 110, 50, 14);
        getContentPane().add(txip);
        txip.setBounds(90, 110, 180, 30);

        btsavepc.setText("Guardar PC");
        btsavepc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsavepcActionPerformed(evt);
            }
        });
        getContentPane().add(btsavepc);
        btsavepc.setBounds(330, 120, 120, 23);

        btsavesala.setText("Guardar Sala");
        btsavesala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsavesalaActionPerformed(evt);
            }
        });
        getContentPane().add(btsavesala);
        btsavesala.setBounds(330, 20, 120, 23);

        btmostrar.setText("Mostrar");
        btmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btmostrar);
        btmostrar.setBounds(40, 210, 100, 23);

        btsalir.setText("Salir");
        btsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btsalir);
        btsalir.setBounds(330, 210, 110, 23);

        setSize(new java.awt.Dimension(499, 293));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btsalirActionPerformed

    private void btsavesalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsavesalaActionPerformed
        // TODO add your handling code here:
        padre.dato=Integer.parseInt(txid.getText());
        list.insertar_nodo_padre_final(padre);
        nuevo();
        javax.swing.JOptionPane.showMessageDialog(this,"Sala Insertada");
        
    }//GEN-LAST:event_btsavesalaActionPerformed

    private void btsavepcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsavepcActionPerformed
        // TODO add your handling code here:
        if(txid.getText().equals(""))
        {
            javax.swing.JOptionPane.showMessageDialog(this,"Digite dato para nodo Padre");
            return;
        }  
        padre.dato=Integer.parseInt(txid.getText());
        hijo.dato=Integer.parseInt(txip.getText());
        list.insertar_nodo_hijo_final(padre, hijo);
        nuevo();
        javax.swing.JOptionPane.showMessageDialog(this,"Hijo Insertado");
    }//GEN-LAST:event_btsavepcActionPerformed

    private void btmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmostrarActionPerformed
        // TODO add your handling code here:
        list.imprimir_padres_hijos();
    }//GEN-LAST:event_btmostrarActionPerformed

    private void txidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_multilista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_multilista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_multilista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_multilista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_multilista().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmostrar;
    private javax.swing.JButton btsalir;
    private javax.swing.JButton btsavepc;
    private javax.swing.JButton btsavesala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txid;
    private javax.swing.JTextField txip;
    // End of variables declaration//GEN-END:variables
}
